# Generated by Django 3.2.3 on 2021-05-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloga',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_img/'),
        ),
    ]
