# Generated by Django 3.2.3 on 2021-05-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta', '0002_bloga_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloga',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posta_img/'),
        ),
    ]
